### ISSUE TITLE
yelp needs PaX flag for WebKitWebProcess

### ISSUE THREAD

**Issue by mckinney-subgraph** [subgraph/sgos_handbook#12]
PaX kills `WebKitWebProcess` when running yelp. A PaX flag need to be added to `/etc/paxrat/paxrat.conf` to view the DocBook version in yelp on Subgraph OS.

The following flag is needed:

```
  "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess": {
    "flags": "m"
  }
```

**Comment by mckinney-subgraph** [comment]
Added the flag to the paxrat repository:
https://github.com/subgraph/paxrat/commit/fb9f027ff4d28a871b995051dd9664a0d0f8331b

**Comment by dma** [comment]
Should we sandbox yelp?
