### ISSUE TITLE
Tried to use it, but...

### ISSUE THREAD

**Issue by DerExilant** [subgraph/sgos_handbook#9]
I'm sorry, after a lot of research and useing google and ixqick, I can not find even the slightest hint on "HowTo login when trying Sugos as life user." Not even in the handbook is a helpful tip, the pages are empty!

**Comment by xSmurf** [comment]
This used to be in the FAQ/Troubleshooting page, we must have mistakenly left it out on the last edit. The password for the live mode is `live`.
